/**
 * Base de datos de prefijos telefónicos para el rastreo geográfico (OSINT).
 */
export const PHONE_PREFIXES = [
  { prefix: '+1 204', country: 'Canadá', city: 'Manitoba' },
  { prefix: '+1 647', country: 'Canadá', city: 'Toronto, Ontario' },
  { prefix: '+1 514', country: 'Canadá', city: 'Montreal, Quebec' },
  { prefix: '+1 604', country: 'Canadá', city: 'Vancouver, BC' },
  { prefix: '+1', country: 'Estados Unidos / Canadá', city: 'Norteamérica' },
  { prefix: '+57 310', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 311', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 312', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 313', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 314', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 315', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 316', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 317', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 318', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 319', country: 'Colombia', city: 'Línea ETB' },
  { prefix: '+57 320', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 321', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 322', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 323', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 324', country: 'Colombia', city: 'Línea Tigo' },
  { prefix: '+57 300', country: 'Colombia', city: 'Línea Claro (Bogotá)' },
  { prefix: '+57 301', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 302', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 303', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 304', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 305', country: 'Colombia', city: 'Línea Claro' },
  { prefix: '+57 350', country: 'Colombia', city: 'Línea Movistar' },
  { prefix: '+57 351', country: 'Colombia', city: 'Línea Movistar' },
  { prefix: '+57 352', country: 'Colombia', city: 'Línea Movistar' },
  { prefix: '+57', country: 'Colombia', city: 'Colombia' },
  { prefix: '+52 55', country: 'México', city: 'Ciudad de México' },
  { prefix: '+52 33', country: 'México', city: 'Guadalajara, Jalisco' },
  { prefix: '+52 81', country: 'México', city: 'Monterrey, Nuevo León' },
  { prefix: '+52', country: 'México', city: 'México' },
  { prefix: '+54 11', country: 'Argentina', city: 'Buenos Aires' },
  { prefix: '+54', country: 'Argentina', city: 'Argentina' },
  { prefix: '+55 11', country: 'Brasil', city: 'São Paulo' },
  { prefix: '+55 21', country: 'Brasil', city: 'Río de Janeiro' },
  { prefix: '+55', country: 'Brasil', city: 'Brasil' },
  { prefix: '+51 1', country: 'Perú', city: 'Lima' },
  { prefix: '+51', country: 'Perú', city: 'Perú' },
  { prefix: '+56 2', country: 'Chile', city: 'Santiago' },
  { prefix: '+56', country: 'Chile', city: 'Chile' },
  { prefix: '+58 212', country: 'Venezuela', city: 'Caracas' },
  { prefix: '+58', country: 'Venezuela', city: 'Venezuela' },
  { prefix: '+593 2', country: 'Ecuador', city: 'Quito' },
  { prefix: '+593', country: 'Ecuador', city: 'Ecuador' },
  { prefix: '+591', country: 'Bolivia', city: 'Bolivia' },
  { prefix: '+595', country: 'Paraguay', city: 'Paraguay' },
  { prefix: '+598', country: 'Uruguay', city: 'Uruguay' },
  { prefix: '+507', country: 'Panamá', city: 'Panamá' },
  { prefix: '+506', country: 'Costa Rica', city: 'Costa Rica' },
  { prefix: '+503', country: 'El Salvador', city: 'El Salvador' },
  { prefix: '+504', country: 'Honduras', city: 'Honduras' },
  { prefix: '+502', country: 'Guatemala', city: 'Guatemala' },
  { prefix: '+505', country: 'Nicaragua', city: 'Nicaragua' },
  { prefix: '+53', country: 'Cuba', city: 'Cuba' },
  { prefix: '+509', country: 'Haití', city: 'Haití' },
  { prefix: '+1 809', country: 'República Dominicana', city: 'Santo Domingo' },
  { prefix: '+34 91', country: 'España', city: 'Madrid' },
  { prefix: '+34 93', country: 'España', city: 'Barcelona' },
  { prefix: '+34', country: 'España', city: 'España' },
  { prefix: '+44 20', country: 'Reino Unido', city: 'Londres' },
  { prefix: '+44', country: 'Reino Unido', city: 'Reino Unido' },
  { prefix: '+33 1', country: 'Francia', city: 'París' },
  { prefix: '+33', country: 'Francia', city: 'Francia' },
  { prefix: '+49 30', country: 'Alemania', city: 'Berlín' },
  { prefix: '+49', country: 'Alemania', city: 'Alemania' },
  { prefix: '+39 06', country: 'Italia', city: 'Roma' },
  { prefix: '+39', country: 'Italia', city: 'Italia' },
  { prefix: '+7 495', country: 'Rusia', city: 'Moscú' },
  { prefix: '+7', country: 'Rusia / Kazajistán', city: 'Rusia' },
  { prefix: '+86 10', country: 'China', city: 'Pekín' },
  { prefix: '+86 21', country: 'China', city: 'Shanghái' },
  { prefix: '+86', country: 'China', city: 'China' },
  { prefix: '+91 11', country: 'India', city: 'Nueva Delhi' },
  { prefix: '+91 22', country: 'India', city: 'Bombay / Mumbai' },
  { prefix: '+91', country: 'India', city: 'India' },
  { prefix: '+234 1', country: 'Nigeria', city: 'Lagos' },
  { prefix: '+234 9', country: 'Nigeria', city: 'Abuja' },
  { prefix: '+234', country: 'Nigeria', city: 'Nigeria' },
  { prefix: '+27 11', country: 'Sudáfrica', city: 'Johannesburgo' },
  { prefix: '+27', country: 'Sudáfrica', city: 'Sudáfrica' },
  { prefix: '+20 2', country: 'Egipto', city: 'El Cairo' },
  { prefix: '+20', country: 'Egipto', city: 'Egipto' },
  { prefix: '+212', country: 'Marruecos', city: 'Marruecos' },
  { prefix: '+971 4', country: 'Emiratos Árabes', city: 'Dubái' },
  { prefix: '+971', country: 'Emiratos Árabes', city: 'Emiratos Árabes Unidos' },
  { prefix: '+966 11', country: 'Arabia Saudita', city: 'Riad' },
  { prefix: '+966', country: 'Arabia Saudita', city: 'Arabia Saudita' },
  { prefix: '+82 2', country: 'Corea del Sur', city: 'Seúl' },
  { prefix: '+82', country: 'Corea del Sur', city: 'Corea del Sur' },
  { prefix: '+81 3', country: 'Japón', city: 'Tokio' },
  { prefix: '+81', country: 'Japón', city: 'Japón' },
  { prefix: '+63 2', country: 'Filipinas', city: 'Manila' },
  { prefix: '+63', country: 'Filipinas', city: 'Filipinas' },
  { prefix: '+62 21', country: 'Indonesia', city: 'Yakarta' },
  { prefix: '+62', country: 'Indonesia', city: 'Indonesia' },
  { prefix: '+60 3', country: 'Malasia', city: 'Kuala Lumpur' },
  { prefix: '+60', country: 'Malasia', city: 'Malasia' },
  { prefix: '+66 2', country: 'Tailandia', city: 'Bangkok' },
  { prefix: '+66', country: 'Tailandia', city: 'Tailandia' },
  { prefix: '+880', country: 'Bangladés', city: 'Daca' },
  { prefix: '+92 51', country: 'Pakistán', city: 'Islamabad' },
  { prefix: '+92', country: 'Pakistán', city: 'Pakistán' },
  { prefix: '+961', country: 'Líbano', city: 'Beirut' },
  { prefix: '+90 212', country: 'Turquía', city: 'Estambul' },
  { prefix: '+90', country: 'Turquía', city: 'Turquía' },
  { prefix: '+380', country: 'Ucrania', city: 'Ucrania' },
  { prefix: '+48', country: 'Polonia', city: 'Polonia' },
  { prefix: '+31', country: 'Países Bajos', city: 'Países Bajos' },
  { prefix: '+32', country: 'Bélgica', city: 'Bélgica' },
  { prefix: '+41', country: 'Suiza', city: 'Suiza' },
  { prefix: '+43', country: 'Austria', city: 'Austria' },
  { prefix: '+46', country: 'Suecia', city: 'Estocolmo' },
  { prefix: '+47', country: 'Noruega', city: 'Oslo' },
  { prefix: '+45', country: 'Dinamarca', city: 'Copenhague' },
  { prefix: '+358', country: 'Finlandia', city: 'Helsinki' },
  { prefix: '+351', country: 'Portugal', city: 'Lisboa' },
  { prefix: '+30', country: 'Grecia', city: 'Atenas' },
  { prefix: '+40', country: 'Rumanía', city: 'Bucarest' },
  { prefix: '+420', country: 'República Checa', city: 'Praga' },
  { prefix: '+36', country: 'Hungría', city: 'Budapest' },
];
